# -*- coding: utf-8 -*-
"""Copy of backend.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aPvFKRI2UzLGNinBS8wGefIUhzj-FMLu
"""

import requests
import json
import pandas as pd
def funct(url):
    response = requests.get(url)
    response_2=response.json()
    # converting json dataset from dictionary to dataframe
    train = pd.DataFrame.from_dict(response_2, orient='columns')
    train.reset_index(level=0, inplace=True)
    yellow=train.at[0,"layer_attribute_data"]
    green=pd.DataFrame.from_dict(yellow, orient='index').transpose()
    red=green.at[0,"attribute_data"]
    df = pd.DataFrame(red)
    df1=pd.DataFrame.from_records(df["properties"].values)
    return df1